### ISSUE TITLE
 No such file or directory - getcwd (Errno::ENOENT)

### ISSUE THREAD

**Issue by clickdees** [kevinhughes27/shopify-sinatra-app#33]
Hi,
Just recently got this error after running the generator. Here is my stacktrace

/home/joey/.rvm/gems/ruby-2.3.1@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:5:in `pwd': No such file or directory - getcwd (Errno::ENOENT)
	from /home/joey/.rvm/gems/ruby-2.3.1@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:5:in `<class:Noexec>'
	from /home/joey/.rvm/gems/ruby-2.3.1@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:3:in `<top (required)>'
	from /home/joey/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /home/joey/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /home/joey/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/joey/.rvm/gems/ruby-2.3.1@global/gems/rubygems-bundler-1.4.4/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
	from /home/joey/.rvm/gems/ruby-2.3.1@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb:50:in `block in run'
	from /home/joey/.rvm/gems/ruby-2.3.1@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb:49:in `each'
	from /home/joey/.rvm/gems/ruby-2.3.1@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb:49:in `run'
	from /home/joey/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:10:in `<main>'

**Comment by clickdees** [comment]
In case anyone has this issue. Here is how I fixed it. I closed and reopened the terminal.
typed 'sudo gem update --system' and that fixed it.
