### ISSUE TITLE
Heroku build stuck on "Detecting rake tasks"

### ISSUE THREAD

**Issue by ClearMarble** [kevinhughes27/shopify-sinatra-app#37]
I've got a basic app set up using your very nice framework that's working great on my dev store when I test installing my local version via ngrok.

Now I'm trying to push to Heroku and the build wont seem to complete. I've been following your instructions very closely, but every time I `git push heroku master` it finishes the bundle install and then hangs on " -----> Detecting rake tasks" until it times out and fails.

I haven't modified the included Rakefile in any way.

Any idea what I might try to do to troubleshoot this? I'll append the log from the last build attempt below in case it's of any use. 

Thanks very much in advance for any assistance you can provide, I really want to get this running!

Heroku Build log:
-----> Ruby app detected
-----> Compiling Ruby/Rack
-----> Using Ruby version: ruby-2.5.0
-----> Installing dependencies using bundler 1.15.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.2). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       Fetching gem metadata from https://rubygems.org/...........
       Fetching version metadata from https://rubygems.org/..
       Fetching dependency metadata from https://rubygems.org/.
       Fetching rake 12.3.0
       Using concurrent-ruby 1.0.5
       Using minitest 5.11.3
       Using thread_safe 0.3.6
       Using builder 3.2.3
       Using arel 8.0.0
       Using encryptor 3.0.0
       Using mini_portile2 2.3.0
       Using bundler 1.15.2
       Fetching dotenv 2.2.1
       Fetching fakeweb 1.3.0
       Installing dotenv 2.2.1
       Installing fakeweb 1.3.0
       Installing rake 12.3.0
       Using multipart-post 2.0.0
       Fetching thor 0.19.4
       Installing thor 0.19.4
       Using graphql 1.8.5
       Using hashie 3.5.7
       Using multi_xml 0.6.0
       Using jwt 1.5.6
       Fetching metaclass 0.0.4
       Installing metaclass 0.0.4
       Using mono_logger 1.1.0
       Using multi_json 1.13.1
       Using mustermann 1.0.2
       Using rack 2.0.4
       Using pg 1.0.0
       Using redis 4.0.1
       Using tilt 2.0.8
       Using tzinfo 1.2.5
       Using attr_encrypted 3.1.0
       Using nokogiri 1.8.4
       Using i18n 0.9.5
       Using faraday 0.12.2
       Using httparty 0.16.2
       Fetching foreman 0.84.0
       Using omniauth 1.8.1
       Using rack-flash3 1.0.5
       Using rack-protection 2.0.1
       Fetching rack-test 0.8.3
       Using vegas 0.1.11
       Using redis-namespace 1.6.0
       Using activesupport 5.1.5
       Using oauth2 1.4.0
       Fetching mocha 1.3.0
       Installing foreman 0.84.0
       Installing rack-test 0.8.3
       Installing mocha 1.3.0
       Using sinatra 2.0.1
       Using activemodel 5.1.5
       Using roxml 4.0.0
       Using graphql-client 0.13.0
       Using omniauth-oauth2 1.5.0
       Using resque 1.27.4
       Using sinatra-redis 0.3.0
       Using activemodel-serializers-xml 1.0.2
       Using activerecord 5.1.5
       Using authorizenet 1.9.5
       Using omniauth-shopify-oauth2 1.2.1
       Using activeresource 5.0.0
       Using sinatra-activerecord 2.0.13
       Using shopify_api 4.12.0
       Using shopify-sinatra-app 0.4.0
       Bundle complete! 13 Gemfile dependencies, 56 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into ./vendor/bundle.
       Bundle completed (4.21s)
       Cleaning up the bundler cache.
       Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.2). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       The latest bundler is 1.16.4, but you are currently running 1.15.2.
       To update, run `gem install bundler`
-----> Detecting rake tasks
-----> Timed out running buildpack Ruby
 !     Timed out compiling app (17 minutes)
 !     See https://devcenter.heroku.com/articles/slug-compiler#time-limit

**Comment by kevinhughes27** [comment]
Super strange. You can check my open source app using this to look for differences: https://github.com/kevinhughes27/shopify-tax-receipts

My app is deployed on heroku-16 stack. I am also using this build pack to run migrations https://github.com/gunpowderlabs/buildpack-ruby-rake-deploy-tasks. The default pack should work fine though.

Please report back when you figure it out!

**Comment by ClearMarble** [comment]
Yeah, it's frustrating...no proper error reported so hard to know where to look. I'm also on heroku-16 Guess I'll try with your app but even if it works I'm not sure where to adjust.

The build passes if I remove rake from the gemfile because of course it gives up trying to detect the rake tasks. In that case I just get:

-----> Detecting rake tasks
       Could not detect rake tasks
       ensure you can run `$ bundle exec rake -P` against your app
       and using the production group of your Gemfile.
       /tmp/build_a4d00f08cbeab1d4d2b4fad22a450328/vendor/ruby-2.5.0/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem rake (>= 0.a) with executable rake (Gem::GemNotFoundException)
       	from /tmp/build_a4d00f08cbeab1d4d2b4fad22a450328/vendor/ruby-2.5.0/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
       	from /tmp/build_a4d00f08cbeab1d4d2b4fad22a450328/vendor/ruby-2.5.0/bin/rake:29:in `<main>'
-----> Discovering process types
       Procfile declares types     -> resque, web
       Default types for buildpack -> console, rake
-----> Compressing...
       Done: 18.1M
-----> Launching...

Do you think there's any way I can skip the automatic rake tasks and run them myself somehow to complete the migration? Apologies if it's a silly question, I'm kind of a Ruby noob still.

**Comment by kevinhughes27** [comment]
I don't think you can skip since its part of how Heroku handles ruby apps. I'd check for version differences in my Gemfile.lock and yours and try forcing a few gem versions (start with Rake)

**Comment by kevinhughes27** [comment]
closing for inactivity

**Comment by josemasuarez** [comment]
Hi, anyone could find any solution about this problem. I've tried multiples solutions but none of these works for me. Could you help me?

**Comment by NemyaNation** [comment]
Install heroku-builds plugin so you can cancel stuck builds:
`heroku plugins:install heroku-builds`

Run `heroku builds:cancel -a YOUR_APP_NAME ` to cancel all your pending builds.

I had an issue where it wasn't deleting all of the pending builds, so I had to find the build on heroku, get the ID and specify it in this format:

`heroku builds:cancel -a YOUR_APP_NAME HEROKU_BUILD_ID`

Install heroku-repo so you can purge the heroku cache, then run your build.
```
heroku plugins:install heroku-repo
heroku repo:purge_cache -a appname
git commit --allow-empty -m "Purge cache"
git push heroku master
```

It will take coinsiderably longer than your regular builds (due to the absense of the cache) but should fix your problem.


----

You could also try just running `git push herkou -f`

----

Make sure nothing is running the background (turn off all background dynos)
